FROM --platform=linux/x86_64 node:16-alpine3.15

WORKDIR /app

RUN apk update && \
    npm i -g npm@7.18.1 && \
    npm i -g next

COPY *.json .
COPY packages/app packages/app 
RUN npm ci

ENV PORT=3000
EXPOSE 3000