FROM --platform=linux/x86_64 node:16-alpine3.15

WORKDIR /app

RUN apk update && \
    npm i -g npm@7.18.1	&& \
    npm i -g @nestjs/cli

COPY *.json .
COPY ./packages/api/*.json ./packages/api/
COPY ./packages/domains/ ./packages/domains
COPY ./packages/infrastructure/ ./packages/infrastructure
RUN npm ci

ENV PORT=3001
EXPOSE 3001