version: "3"

services:
  workspace-worker:
    working_dir: /app
    container_name: workspace-worker
    build: 
      context: .
      dockerfile: docker/api/Dockerfile.dev
    env_file: .env
    ports:
      - 3001:3001
    depends_on:
      - workspace-database
    volumes:
      - ./packages/api/src:/app/packages/api/src
      - ./packages/api/dist:/app/packages/api/dist
      - ./packages/domains/dist:/app/packages/domains/dist
      - ./packages/infrastructure/dist:/app/packages/infrastructure/dist
    command: npm run dev:server

  migration-container:
    build: 
      context: .
      dockerfile: docker/batch/Dockerfile
    env_file: .env
    depends_on:
      - workspace-database
    volumes:
      - ./packages/batch/src/migrations:/app/packages/batch/src/migrations

  workspace-database:
    image: postgres:14-alpine
    container_name: workspace-database
    ports: 
      - 5433:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: workspace-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

