version: "3"

services:
  workspace-worker:
    working_dir: /app
    container_name: workspace-worker
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file: .env
    ports:
      - 3001:3001
    volumes:
      - ./packages/api/src:/app/packages/api/src
      - ./packages/api/dist:/app/packages/api/dist
    depends_on:
      - workspace-database
    command: npm run dev:server

  workspace-database:
    image: postgres:14-alpine
    container_name: workspace-database
    ports: 
      - 5555:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: workspace-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

