FROM --platform=arm64 node:16-alpine3.15

WORKDIR /app

RUN apk update && \
    npm i -g npm@7.18.1	&& \
    npm i -g @nestjs/cli

COPY *.json .
COPY ./packages/api/*.json ./packages/api/
RUN npm ci

ENV PORT=3001
EXPOSE 3001