import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { GetStaticProps, GetStaticPropsContext } from 'next'
import * as AmazonCognitoIdentity from 'amazon-cognito-identity-js';

const inter = Inter({ subsets: ['latin'] })

type PropsType = Record<"pool", AmazonCognitoIdentity.ICognitoUserPoolData>

export default function Home(props: PropsType) {
  const loginHandler = async() => {}
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <button onClick={loginHandler}>
            <p>login</p>
          </button>
        </div>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps<PropsType> = async (_: GetStaticPropsContext) => {
  return { 
    props: { 
      pool: {
        UserPoolId: process.env.POOL_ID as string,
        ClientId: process.env.CLIENT_ID as string,
      }
  } 
}
}
